version: '3'
services:
  fpm:
    image: php:fpm
    volumes:
      - ./app:/var/www/html
    ports:
      - "9000:9000"
  nginx:
    image: nginx:stable
    depends_on:
      - fpm
    volumes:
      - ./conf/nginx:/etc/nginx/conf.d/default.conf
      - ./app:/var/www/html
      - ./logs/nginx:/var/log/nginx
    ports:
      - "80:80"
    links:
      - fpm
  dokuwiki:
    build: .
    volumes:
      - ./app:/var/www/html
      - ./bootstrap.sh:/usr/local/bin/bootstrap.sh
