version: '2'
services:
  fpm:
    image: php:fpm
    volumes:
      - ./app:/var/www/html
    ports:
      - "9000:9000"
    links:
      - mysql
  nginx:
    image: nginx:stable
    volumes:
      - ./conf/nginx:/etc/nginx/conf.d/default.conf 
      - ./app:/var/www/html
      - ./logs/nginx:/var/log/nginx
    ports:
      - "80:80"
      - "443:443"
    links:
      - fpm
  mysql:
    image: mysql:5.7
    restart: always
    ports:
      - "3306:3306"
    environment:
      - MYSQL_ROOT_PASSWORD=root
      - MYSQL_DATABASE=my_db
    volumes:
      - ./data/db:/var/lib/mysql